### ISSUE TITLE
How to make scrollbars huge?

### ISSUE THREAD

**Issue by ViktorNova** [luebking/virtuality#21]
One of the things I love the most about Bespin was being able to make the scrollbars ridiculously oversized, which makes using QT4 on a touchscreen very doable. Is there any way to accomplish this for Virtuality, even if it's not in the gui yet?

**Comment by ViktorNova** [comment]
Thank you for your reply - I did not know about that. Is this a hack of yours, or that feature just part of QT4/5? I'm assuming it is something in the code level and not a feature provided by the QT theme, correct?

Resizable scrollbars would be really great, although I should be able to just adjust it in the code and build my own for the time being. Thanks!

**Comment by luebking** [comment]
"Hack"
The mouse movements are intercepted and translated into an adjustment of the current value of the scrollarea.

commit 5257fa3d25b3506c913d2524a441aabcd0a1aa64

virtuality write style Slider.Thickness 22 # default is 11
