### ISSUE TITLE
plasma5: plasmashell context menu is completely transparent

### ISSUE THREAD

**Issue by ff2000** [luebking/virtuality#22]
It seems like the background doesn't get filled. As I use a dark color scheme (Dark Breeze) and do not invert menu colours the context menu is barely readable (white text in front of translucent background). It get's slightly better if I enable translucency and blur, but it still is hard to read.

**Comment by luebking** [comment]
commit 738404868fdfb56ba2eaf85fb6c09b4e7f3cf878

**Comment by luebking** [comment]
plasmashell gemurkse mit transparenten Menüs.
Bei mir ist DarkBreeze übrigens "weiß", sofern contrast und blur deaktiviert sind und transparent, sofern der contrast effekt deaktiviert ist *LOL* =)
