### ISSUE TITLE
Unreadable text in Plasma

### ISSUE THREAD

**Issue by beojan** [luebking/virtuality#23]
Where the background is drawn by Plasma (e.g. KScreenLocker, KRunner), and a dark plasma theme is used with a dark text color in virtuality, text in line entries is hard to read.

This could be fixed by using the Plasma foreground color instead of the Virtuality text color when the background is drawn by Plasma.

**Comment by luebking** [comment]
> This could be fixed by using the Plasma foreground color

Virtuality doesn't link kdelibs or KF/5 - let alone plasma.

Leaving that aside, I assume this relates to lineedits?
In case: the style doesn't paint the text anyway.

Virtuality currently checks whether the application is Plasma (plasma-desktop, but "krunner" should be matched as well?) and paints a solid background ("like other styles") - probably the only solution as long as plasma goes by this "half-overriding the style" approach.

Is this "KDE SC4" or "Plasma Next" (aka KDE4 or KDE5)?

**Comment by beojan** [comment]
Plasma 4. Also, you may need to match kscreenlocker explicitly too.

Sincerely,
Beojan Stanislaus

**Comment by luebking** [comment]
"kscreenlocker_greet" - krunner is "odd" - apparently the widget has initially no custom palette set (until you start typing)

commit e38d1a1b819e6ad70bc0fef3c8ecb54f0128d499
