### ISSUE TITLE
XBar

### ISSUE THREAD

**Issue by beojan** [luebking/virtuality#29]
Given there is no plasma 5 XBar plasmoid, can you please document the XBar api / protocol?

**Comment by luebking** [comment]
Server:

method Q_NOREPLY void org.kde.XBar.addEntry(qlonglong key, int idx, QString entry)
method Q_NOREPLY void org.kde.XBar.changeEntry(qlonglong key, int idx, QString entry)
method Q_NOREPLY void org.kde.XBar.registerMenu(QString service, qlonglong key, QString title, QStringList entries)
method Q_NOREPLY void org.kde.XBar.releaseFocus(qlonglong key)
method Q_NOREPLY void org.kde.XBar.removeEntry(qlonglong key, int idx)
method Q_NOREPLY void org.kde.XBar.reparent(qlonglong oldKey, qlonglong newKey)
method Q_NOREPLY void org.kde.XBar.requestFocus(qlonglong key)
method Q_NOREPLY void org.kde.XBar.setOpenPopup(int idx)
method Q_NOREPLY void org.kde.XBar.unregisterMenu(qlonglong key)

client:

method Q_NOREPLY void org.kde.XBarClient.activate()
method Q_NOREPLY void org.kde.XBarClient.deactivate()
method Q_NOREPLY void org.kde.XBarClient.hover(qlonglong key, int idx, int x, int y)
method Q_NOREPLY void org.kde.XBarClient.popDown(qlonglong key)
method Q_NOREPLY void org.kde.XBarClient.popup(qlonglong key, int idx, int x, int y)
method Q_NOREPLY void org.kde.XBarClient.raise(qlonglong key)

**Comment by beojan** [comment]
Thank you

**Comment by beojan** [comment]
So the menu is actually displayed by the client, not the plasmoid?

**Comment by luebking** [comment]
The popup is, the menubar not.
I deemed transferring the popup into the server too wonky (encounters limitations with widget actions and the async nature of IPC is prone to clash with possible sync expectations in the client) - the various dbusmenu caused issues (messed up order, missing items, ...) seem to prove me right (and canonical actually aborted dbusmenu for whatever is their new technique de toujours)
